name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jfrog/fly-action@v1
        with:
          fly-token: ${{ secrets.FLY_TOKEN }}

      - name: Run a simple test
        run: echo "Hello from CI"
